### ISSUE TITLE
Ability to use `<%= ... %>` in markdown templates

### ISSUE THREAD

**Issue by sickill** [boydm/phoenix_markdown#1]
phoenix_markdown uses `EEx.compile_string` so I thought I could embed eex tags in my `.html.md` templates, however this is what happens (pipeline taken from `engine.ex`):

    iex(1)> "foo <%= 1 + 2 %> bar" |> Earmark.to_html |> EEx.compile_string(engine: Phoenix.HTML.Engine, file: "a", line: 1)
    {:safe, [{:|, [], ["", "<p>foo &lt;%= 1 + 2 %&gt; bar</p>\n"]}]}

Earmark is html-encoding `<` character so the whole eex `<%= >` tag is broken. I know this is not phoenix_markdown fault (and probably neither earmark's), however I am still wondering if we can make it work somehow.

**Comment by boydm** [comment]
Markdown files are static in nature.
I would move this page to an eex template, then use Earmark to render the portion that is in markdown.

**Comment by sickill** [comment]
This is what I did. Thanks for the lib btw!

**Comment by boydm** [comment]
By the way. If you look at the new version of phoenix_markdown, which is currently in Master, I've added support for <%= %>...

Probably putting in Hex later this week.
