### ISSUE TITLE
Dependency errors with newer versions of Phoenix

### ISSUE THREAD

**Issue by clintgibler** [boydm/phoenix_markdown#5]
Thanks for making this @boydm! 

I'm trying to use `phoenix_markdown` with a newer version of Phoenix but I'm getting a dependency error:

```
Running dependency resolution...

Failed to use "phoenix" (version 1.3.0-rc.2) because
  phoenix_live_reload (version 1.0.8) requires ~> 1.0 or ~> 1.2-rc
  phoenix_markdown (versions 0.1.0 to 0.1.4) requires ~> 1.1 *  <-- This is in red
  mix.lock specifies 1.3.0-rc.2

* This requirement does not match pre-releases. To match pre-releases include a 
pre-release in the requirement, such as: "~> 2.0-beta".

** (Mix) Hex dependency resolution failed, relax the version requirements of your 
dependencies or unlock them (by using mix deps.update or mix deps.unlock). If
you are unable to resolve the conflicts you can try overriding with 
{:dependency, "~> 1.0", override: true}
```
Is this library forward compatible with newer versions of Phoenix (e.g. 1.3.0-rc.2+)? If so, could this be solved by bumping or making more broad the version of Phoenix `phoenix_markdown` relies on?

Thanks for your time.

**Comment by boydm** [comment]
Looking at it... This appears to be an issue because hex dependencies do not match to .rc releases unless explicitly specified. Not sure how, or even if, I should get around that. Once Phoenix 1.3 releases, I think it will work just fine.

Try adding :override to your phoenix dependency line and let me know if that works.

**Comment by clintgibler** [comment]
Thanks for the response. 

Changing the phoenix dependency line in `mix.exs` did work:

```elixir
defp deps do
    [{:phoenix, "~> 1.3.0-rc", override: true},
      ...
    {:phoenix_markdown, "~> 0.1"}]
end
```
