### ISSUE TITLE
How can I render markdown data into the template 

### ISSUE THREAD

**Issue by AlmogRnD** [boydm/phoenix_markdown#7]
I wanted to know how I can render markdown data into the template if that is possible? 

I have the following 

```
<%= for magnet <- @magnets do %>
            <div class="col-md-6">
                <div class="card card-bordered style-primary">
                    <div class="card-head">
                        <div class="tools">
                            <div class="btn-group">
                                <%= link to: magnet_path(@conn, :edit, magnet), class: "btn btn-icon-toggle btn-refresh" do %>
                                    <span class="md md-edit"></span>
                                 <% end %>
                                 <%= link to: magnet_path(@conn, :delete, magnet), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-icon-toggle btn-refresh" do %>
                                     <span class="md md-delete"></span>
                                 <% end %>
                            </div>
                        </div>
                        <%= link to: magnet_path(@conn, :show, magnet), class: "" do %>
                         <header><i class="fa fa-fw fa-tag"></i><%= magnet.title %></header>
                        <% end %>
                    </div>
                    <!--end .card-head -->
                    <div class="card-body style-default-bright">
                        <p>
                            <%= magnet.description %>
                        </p>
                    </div>

                     <div class="card-body style-default-bright">
                                            <p>
                                                <%= render "markdown_render.html", assigns %>
                                            </p>
                                        </div>



                </div>
            </div>
            <% end %>
```

and  `<%= magnet.content %>` is markdown 

How can I have that render inside the`  <%= render "markdown_render.html", assigns %>`

**Comment by boydm** [comment]
Let me see if I understand the question.

`<%= magnet.content %>` is a markdown string, but the `"markdown_render.html"` template is html and not markdown. Correct?

Is `magnet.content` created/retrieved/whatever from a controller?

If `magnet.content` is a markdown string you loaded from a controller, then you should render it directly using Earmark (which is what markdown_phoenix is doing behind the scenes).

Something like this: `<%= Earmark.as_html!(magnet.content, options) %>`. Where you choose the appropriate Earmark options behind the scene.

If the template itself is markdown, and not directly html, then it should have the .md extension instead of .html

Hope this helps!

**Comment by AlmogRnD** [comment]
@boydm thanks that was it, just need to do the following 

` <%= Earmark.as_html!(magnet.content) %>`

Any idea why it's not rendering the HTML I'm just getting the following 

<img width="1089" alt="screen shot 2018-05-11 at 2 58 55 pm" src="https://user-images.githubusercontent.com/169507/39907401-de80c674-552b-11e8-95e3-9cda58ea259d.png">

So I see it outputting HTML but not getting rendered

**Comment by boydm** [comment]
You probably need to mark it as html safe.
See docs here: https://hexdocs.pm/phoenix_html/Phoenix.HTML.html

Try it like this:  `<%= {:safe, Earmark.as_html!(magnet.content)} %>`

**Comment by AlmogRnD** [comment]
Thanks need to use raw got it working clsoing this
